# Generated by Django 4.1 on 2022-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('alternative_phone_number', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('PR', 'Parent'), ('GR', 'Guardian')], default='Parent', max_length=20)),
                ('id_number', models.IntegerField()),
                ('occupation', models.CharField(choices=[('EP', 'Employed'), ('CL', 'Casual'), ('UE', 'Unemployed')], default='Employed', max_length=20)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, default='', null=True, upload_to='profiles')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('birth_certificate_number', models.CharField(max_length=15)),
                ('calling_letter_number', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_level_certificate_number', models.CharField(max_length=20)),
                ('entry_grade', models.CharField(max_length=20)),
                ('date_of_joining', models.DateTimeField()),
                ('graduation_year', models.DateField()),
                ('level', models.CharField(choices=[('F1', 'Form One'), ('F2', 'Form Two'), ('F3', 'Form Three'), ('F4', 'Form Four')], default='Form One', max_length=20)),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.parent')),
                ('subjects', models.ManyToManyField(to='students.subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['first_name'],
            },
        ),
    ]
