# Generated by Django 4.1 on 2022-09-01 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 1, 4, 29, 55, 520725, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
