# Generated by Django 4.1 on 2022-09-01 04:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Education Levels',
                'verbose_name_plural': 'Education Level',
            },
        ),
        migrations.CreateModel(
            name='TeacherDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Teacher Designation',
                'verbose_name_plural': 'Teacher Designations',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(default=datetime.datetime(2022, 9, 1, 4, 26, 15, 708596, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(max_length=30)),
                ('contract', models.CharField(blank=True, choices=[('CT', 'Contract'), ('PT', 'Part Time'), ('PNT', 'Permanent')], max_length=20, null=True)),
                ('id_number', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('on_duty', models.BooleanField(blank=True, default=False, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True)),
                ('on_probation', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=30, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('class_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.class')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.teacherdesignation')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.educationlevel')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', records.models.CustomDateTimeField()),
                ('time_out', records.models.CustomDateTimeField()),
                ('present', models.BooleanField(blank=True, default=True, null=True)),
                ('weekend', models.CharField(blank=True, choices=[('WD', 'Weekday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('HD', 'Holiday')], max_length=100, null=True)),
                ('reason_for_absence', models.TextField(blank=True, max_length=500, null=True)),
                ('absent_with_permission', models.BooleanField(blank=True, default=True, null=True)),
                ('permission_by_teacher', models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.teacher')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
