# Generated by Django 4.1 on 2022-08-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0, help_text='Number of students')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'EducationLevel',
                'verbose_name_plural': 'EducationLevel',
            },
        ),
        migrations.CreateModel(
            name='TeacherDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'TeacherDesignation',
                'verbose_name_plural': 'TeacherDesignation',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('joining_date', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('on_probation', models.BooleanField(default=False)),
                ('email_address', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(default=0)),
                ('id_number', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contract', models.CharField(choices=[('CT', 'Contract'), ('PT', 'Part Time'), ('PNT', 'Permanent')], max_length=20)),
                ('certificate_number', models.CharField(max_length=30)),
                ('on_duty', models.BooleanField(blank=True, default=False, null=True)),
                ('class_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.class')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.teacherdesignation')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.educationlevel')),
                ('subjects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('weekend', models.CharField(choices=[('WD', 'Weekday'), ('SAT', 'Saturday'), ('SUN', 'Sunday'), ('HD', 'Holiday')], max_length=100)),
                ('present', models.BooleanField(default=True)),
                ('reason_for_absence', models.TextField(blank=True, max_length=500, null=True)),
                ('absent_with_permission', models.BooleanField(blank=True, default=True, null=True)),
                ('permission_by_teacher', models.ForeignKey(blank=True, default='N/A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.teacher')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
