# Generated by Django 4.1 on 2022-09-01 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 1, 4, 29, 55, 527707, tzinfo=datetime.timezone.utc)),
        ),
    ]
